service: monty-cloud-assessment

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  layers:
      -  arn:aws:lambda:us-east-1:017000801446:layer:AWSLambdaPowertoolsPythonV2:40
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: 
        - arn:aws:sqs:${self:provider.region}:${aws:accountId}:ThumbnailQueue
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - arn:aws:s3:::${self:custom.s3}/*
        - arn:aws:s3:::${self:custom.s3}

custom:
  s3: montys3-thumbnail-creator
  queue: https://sqs.${self:provider.region}.amazonaws.com/${aws:accountId}/ThumbnailQueue
  region: us-east-1

functions:
  imageProcessor:
    handler: lambda_handlers/processor.image_processor
    environment:
      s3: ${self:custom.s3}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ThumbnailQueue
              - Arn
      # - s3:
      #     bucket: ${self:custom.s3}
      #     event: s3:ObjectCreated:*
      #     rules:
      #       - prefix: uploads/

  uploadImage:
    handler: lambda_handlers/uploader.image_uploader
    environment:
      queue: ${self:custom.queue}
      s3: ${self:custom.s3}
    events:
      - http:
          path: upload/image
          method: post         

# you can add CloudFormation resource templates here
resources:
  Resources:
    ThumbnailQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ThumbnailQueue

    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3}                   
