service: monty-cloud-assessment

frameworkVersion: '3'

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  layers:
      -  arn:aws:lambda:us-east-1:017000801446:layer:AWSLambdaPowertoolsPythonV2:40
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: 
        - arn:aws:sqs:${self:provider.region}:${aws:accountId}:ThumbnailQueue
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - arn:aws:s3:::${self:custom.s3}/*
        - arn:aws:s3:::${self:custom.s3}

custom:
  s3: montys3-thumbnail-creator
  queue: https://sqs.${self:provider.region}.amazonaws.com/${aws:accountId}/ThumbnailQueue
  region: us-east-1
  pythonRequirements:
    dockerizePip: true
    zip: true

# package: 
#   include:
#     - "Pillow"
#     - "*.py"

functions:
  imageProcessor:
    handler: lambda_handlers/processor.image_processor
    environment:
      s3: ${self:custom.s3}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ThumbnailQueue
              - Arn

  uploadImage:
    handler: lambda_handlers/uploader.image_uploader
    environment:
      queue: ${self:custom.queue}
      s3: ${self:custom.s3}
    events:
      - http:
          path: upload/image
          method: post

  uploadEncodedImage:
    handler: lambda_handlers/encoded_uploader.image_uploader
    environment:
      queue: ${self:custom.queue}
      s3: ${self:custom.s3}
    events:
      - http:
          path: upload/imagetest
          method: post

  downloader:
    handler: lambda_handlers/downloader.image_downloader
    environment:
      s3: ${self:custom.s3}
    events:
      - http:
          path: download/{key}
          method: get                

# you can add CloudFormation resource templates here
resources:
  Resources:
    ThumbnailQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ThumbnailQueue

    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3}                   
